### ISSUE TITLE
Bug: In segment override tab, value type not changing from default text to other type.

### ISSUE THREAD

**Issue by harenlewis** [Flagsmith/flagsmith#106]
Hi team,

Great work on the new version of Bullet Train - Flagsmith! Appreciate all the new features and functionalities.
We are back to integrating Flagsmith and came across a bug which looks like a minor issue.

Steps:
1. Create a flag and add a value with type JSON.
2. Go to the Overrides tab select a segment
3. Now in the segment, try to select a different type other than text, it does not reflect as the corresponding input.

Please let me know if I can provide more context or need any more information on this.
Thank you.

**Comment by kyle-ssg** [comment]
A fix for this is now in production.
