### ISSUE TITLE
Mark flags as deprecated

### ISSUE THREAD

**Issue by amweiss** [Flagsmith/flagsmith#112]
We currently have a use case around features that are being phased out but can't be deleted yet due to old mobile clients still referencing it.

Is there a way to tag/mark the features as deprecated to be able to hide them from the UI without deleting them? Otherwise, I would like to request that feature.

Right now, adding a tag could work, but it only is a positive match filter rather than "anything except this tag".
![image](https://user-images.githubusercontent.com/30146/121692331-ff792780-ca95-11eb-9e89-3329d182a877.png)

**Comment by kyle-ssg** [comment]
Hey, yep I see what you mean - currently no but it’s a sensible suggestion. Will take a look!

**Comment by kyle-ssg** [comment]
I think the better solution here is to simply preselect all tags when the features page is loaded so that a tag like deprecated can be deselected. This has been done as part of https://github.com/Flagsmith/flagsmith/pull/114.

![image](https://user-images.githubusercontent.com/8608314/121785294-ea44eb80-cbb0-11eb-8bc0-0adbdb2134e9.png)


@dabeeeenster can be closed when new GH pipelines are sorted.

**Comment by dabeeeenster** [comment]
OK pipeline now builds to production on merges to `main` - about to merge this in

**Comment by kyle-ssg** [comment]
@amweiss This is now live, feel free to message back here if there are any issues.

**Comment by kyle-ssg** [comment]
Reopening this, it needs a slightly different solution in order to support non-tagged features.

**Comment by dabeeeenster** [comment]
I think it would be go better to have a ‘hide flags in dashboard by default’ boolean stored against a tag. You can then create a tag called e.g `deprecated` and select the `hide by default` option. 

The tag itself would still show up on the dashboard but would default to deselected, and none of the flags tagged with it would show initially.

**Comment by dabeeeenster** [comment]
Best option would be to store the selected/deselected tags against the user account (as a flagsmith trait) and default to those.

**Comment by kyle-ssg** [comment]
This is now live, tags are persisted and you can filter by untagged.
