### ISSUE TITLE
We are storing a trait for dark mode but it doesnt appear to be used in the code? 

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#133]
Should this persist dark mode preferences against the user?

**Comment by kyle-ssg** [comment]
Not true.

**Comment by dabeeeenster** [comment]
Hmm this is erroring in an on prem install

**Comment by kyle-ssg** [comment]
Toggling the switch sets the trait against the user, which puts them into the dark_mode segment, which enables the dark mode feature.

It works in production, therefore not a bug.

**Comment by dabeeeenster** [comment]
Added the segment to the docs for self hosting.
