### ISSUE TITLE
Self hosted installations should not prompt to upgrade plan etc

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#134]
We should set an ENV VAR `PAYMENTS_ENABLED` in the SaaS platform (front end I think?). If that is set, we should show options that are only relevant for SaaS:

- upgrading your account
- seat limits 
- manage invoice/payment plan

**Comment by kyle-ssg** [comment]
Is there any API to this at all @matthewelwell ? This could all be frontend maybe.

**Comment by dabeeeenster** [comment]
I think it would be ok to have as an environment variable on the front end. `SELF_HOSTED` boolean which defaults to `True`. This would remove the SaaS prompts/notifications.

**Comment by dabeeeenster** [comment]
This issue is linked with #141  - can do both in one PR I would think.

**Comment by matthewelwell** [comment]
Yeah, all sounds reasonable to me. I don't think there's any API needed. Let me know if that's not the case.

**Comment by kyle-ssg** [comment]
Rather than an env var, this is a feature flag "payments_enabled"

**Comment by dabeeeenster** [comment]
How does this leave the default experience when starting a new self hosted application?

**Comment by kyle-ssg** [comment]
What does that mean?
