### ISSUE TITLE
Cannot create segments (Error: Cannot read property 'reduce' of null)

### ISSUE THREAD

**Issue by guatedude2** [Flagsmith/flagsmith#139]
Hello, i'm having an issue when trying to add a new segment. When I click "Create your first Segment". I tried creating the segment from the DB but I get the same error when editing the segment.

Running Flagsmith locally
- flagsmith/flagsmith-api:v2.7.1
- flagsmith/flagsmith-frontend:v2.7.0

<img width="887" alt="Screen Shot 2021-06-18 at 2 57 39 PM" src="https://user-images.githubusercontent.com/918429/122605499-88b7cd80-d045-11eb-8f45-f05e39cffb35.png">

```
react-select.esm.js:4071 Uncaught TypeError: Cannot read property 'reduce' of null
    at t.value (react-select.esm.js:4071)
    at new t (react-select.esm.js:3541)
    at Jo (react-dom.production.min.js:150)
    at ta (react-dom.production.min.js:162)
    at ja (react-dom.production.min.js:192)
    at Aa (react-dom.production.min.js:193)
    at fi (react-dom.production.min.js:205)
    at Ra (react-dom.production.min.js:200)
    at vi (react-dom.production.min.js:218)
    at bi (react-dom.production.min.js:218)
```

**Comment by dabeeeenster** [comment]
Are you running the application with docker-compose or in some other manner?

**Comment by kyle-ssg** [comment]
Hi @guatedude2 I presume here the issue is that you’re running the frontend against your own flagsmith environment which hasn’t got the necessary feature flags and remote config setup.

https://docs.flagsmith.com/deployment/locally-frontend#running-locally-against-your-own-flagsmith-api-instance

In particular you need the segment operators config defined here
https://gist.github.com/kyle-ssg/55f3b869c28bdd13c02c6688bc76c67f

Please reopen if this isn’t the case or doesn’t make sense, but I’m pretty certain this is the issue.

**Comment by dabeeeenster** [comment]
@kyle-ssg maybe we should have a better error message to the user here?

**Comment by guatedude2** [comment]
@kyle-ssg is right. I forgot to add the `segment_operators`. I think hiding the segments section when the operators are missing makes more sense or just have a default set of operators rather than a reduce error. 

Particularly because you can’t really do anything with segments without the operators.

**Comment by kyle-ssg** [comment]
Will keep this open until we deploy a suitable message for this.

**Comment by kyle-ssg** [comment]
The following will now show for self hosted without a remote config value for segment_operators.

![image](https://user-images.githubusercontent.com/8608314/122646024-275f2f80-d115-11eb-9374-b8e7a53c9439.png)
![image](https://user-images.githubusercontent.com/8608314/122646108-7dcc6e00-d115-11eb-8017-4757987da45f.png)

**Comment by guatedude2** [comment]
Amazing! Thanks @kyle-ssg

**Comment by kyle-ssg** [comment]
No worries, thanks for reporting! 👍
