### ISSUE TITLE
Attempting to create an already existing Identity in the Front End silently errors

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#144]
We should catch this case and show a better message in the front end. 

![image](https://user-images.githubusercontent.com/173290/122807588-ac884700-d2c3-11eb-99e8-69f903f032c4.png)
![image](https://user-images.githubusercontent.com/173290/122807616-b3af5500-d2c3-11eb-9f49-8ac2e1e36989.png)

**Comment by kyle-ssg** [comment]
This is by design, if you paste 100 identities we don’t want it to fail because of 1?

**Comment by dabeeeenster** [comment]
> This is by design, if you paste 100 identities we don’t want it to fail because of 1?

That's fine, but the current UX is not sufficient.

**Comment by dabeeeenster** [comment]
I think "Some Identities already exist and were not created" would be fine.

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/pull/211
