### ISSUE TITLE
Self-hosted Flagsmith not rendering favicon correctly on Chrome

### ISSUE THREAD

**Issue by alfieyfc** [Flagsmith/flagsmith#145]
Using Chrome, the favicon isn't rendering as shown in screenshots below when connecting to my self-hosted FQDN via CloudFlare

![image](https://user-images.githubusercontent.com/41598103/122900999-b8d1da00-d37f-11eb-8639-a63ed4519bb1.png)

But when port-forwarded the instance to my localhost (the instance is running on Kubernetes), favicon can render correctly.

![image](https://user-images.githubusercontent.com/41598103/122902061-bb80ff00-d380-11eb-9649-98d6aa493435.png)

---

Using different browsers (I tried both Vanilla Firefox & Tor), favicon can also render correctly.

![image](https://user-images.githubusercontent.com/41598103/122903035-9771ed80-d381-11eb-9398-766f228a7cb6.png)

---

I opened developer tools on the browser and searched for this line. After finding [this post on s.o.](https://stackoverflow.com/a/28920035), I added a `?` directly to the end of `href`, then the favicon renders.

![image](https://user-images.githubusercontent.com/41598103/122901295-ff273900-d37f-11eb-8592-284be3d52f45.png)

![image](https://user-images.githubusercontent.com/41598103/122903927-7362dc00-d382-11eb-9a71-0a555b2f3fd7.png)

---

With all information above, I don't have sufficient knowledge to tell if it's a browser issue, CloudFlare issue, deployment issue, or a code issue... hence decided to ask here.

### More Info
Browser: Chrome Version 91.0.4472.114 (Official Build) (64-bit)
Flagsmith Version: `v2.6.0` deployed to Kubernetes via Helm chart [`flagsmith-0.2.14`](https://github.com/Flagsmith/flagsmith-charts/releases/tag/flagsmith-0.2.14)

**Comment by dabeeeenster** [comment]
Hi @alfieyfc - thanks for a very comprehensive bug report - this is not something we would be able to look into I'm afraid; I would expect it to be something within your infrastructure setup.

**Comment by alfieyfc** [comment]
Oh okay, I assume you don't think missing a `?` in `href` is what caused the issue then. Thanks for the quick reply. 🙏

**Comment by dabeeeenster** [comment]
I've no idea to be honest! But I don't to start adding aspects like this based on external CDNs etc

**Comment by alfieyfc** [comment]
I see. I'll reopen if I can confirm in advanced that it's code related then. 👌

**Comment by dabeeeenster** [comment]
OK great thanks
