### ISSUE TITLE
Load testing profile

### ISSUE THREAD

**Issue by sjdines** [Flagsmith/flagsmith#15]
Hi, I was wondering if you have done any load testing profiling to know of any potential scalability issues as well as the performance characteristics?

**Comment by matthewelwell** [comment]
Hi @sjdines, so far no formalised load testing has been done against the application. From our current level of testing, the application performs very well, however it is on our roadmap to do some more thorough load testing.

**Comment by matthewelwell** [comment]
Thanks @sjdines I'll try to take a look into it too.

**Comment by dabeeeenster** [comment]
Hi @sjdines. Recent API commits have had some performance tweaks (mainly around optimising the Django ORM calls). On a single desktop machine we can serve around 500 flags per second. In production we are now serving millions of flags a day easily on 2 load balanced AWS nano instances.
