### ISSUE TITLE
Refactor SDKs to new Namespace (Bullet Train > Flagsmith)

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#159]
The following SDKs need updating to rebrand from Bullet Train to Flagsmith

- [x] [DotNet](https://github.com/Flagsmith/flagsmith-dotnet-client)
- [x] [Python](https://github.com/Flagsmith/flagsmith-python-client)
- [x] [iOS](https://github.com/Flagsmith/flagsmith-ios-client)
- [x] [Rust](https://github.com/Flagsmith/flagsmith-rust-client)
- [x] [Go](https://docs.flagsmith.com/clients/go/)

Create a new project in the relevant language package manager with the new namespace of `Flagsmith`. Add a message that the old Bullet Train library is deprecated.

**Comment by gagantrivedi** [comment]
@dabeeeenster  This one is ready to be closed.
