### ISSUE TITLE
Build an onboarding flow for new installations

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#162]
When a new installation starts up for the first time (against an empty database), the user should be directed to an onboarding/setup page. This would ask for:

- Django Super User details:
   - Name
   - Email Address 
   - Password
- `django_site` table domain and name

This should only show up once - after it has been completed it should be locked down and never shown again.

**Comment by matthewelwell** [comment]
I think that this can be achieved instead with the fixtures that @gagantrivedi created?

**Comment by gagantrivedi** [comment]
It can be, but that will be more static.

**Comment by dabeeeenster** [comment]
I think shipping with default passwords is a bad idea? This data is specific to the person installing flagsmith.

**Comment by matthewelwell** [comment]
Yep, ok, I agree. As discussed this morning let's continue with a more polished option that adds a page to handle this information. 

I suggest that we do the following: 

1. On startup (using the `ready` method of the `AppConfig` in one of the apps - TBD which one), check whether a super user exists in the system, if it does, do nothing, if it doesn't log a warning that states something along the lines of: 

```
YOUR INSTALLATION IS INSECURE: PLEASE ACCESS https://the.domain.com/config/init TO CREATE A SUPER USER
```

2. Create a page which allows anonymous users (aka. is public) but has some permission class on it that checks if there is a super user already in the system or not and denies access if there is. This page should be a simple `FormView` which has the fields defined above and creates the super user / updates the default `Site` object.

**Comment by dabeeeenster** [comment]
Its going to be almost impossible to reliably guess/figure out the DNS name for the server. So maybe just something like:

```
YOUR INSTALLATION IS INSECURE: PLEASE ACCESS http://<your-server-domain:8080>/config/init TO CREATE A SUPER USER
```

**Comment by matthewelwell** [comment]
Very true, yes.
