### ISSUE TITLE
Calls to /environments/<env id>/identities is slow in Production

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#169]
Looks like the ORM is doing something suboptimal.

**Comment by dabeeeenster** [comment]
This is still slow

**Comment by kyle-ssg** [comment]
Still seems to be taking 4s with an org with 1 identity

**Comment by dabeeeenster** [comment]
Some previously slow endpoints are faster but some are still slow

**Comment by dabeeeenster** [comment]
OK this is 100% fixed now guarantee it 100% 110%
