### ISSUE TITLE
Add request headers to traits available to segment rules

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#171]
It would be nice to be able to write segment rules using HTTP request headers as trait values. E.g a browser might send the following HTTP Request header through:

```
accept-language: en-GB,en-US;q=0.9,en;q=0.8
```

We could then enable users to add a segment rule based on this data as a transient trait, with the name `header:accept-language` and the value `en-GB,en-US;q=0.9,en;q=0.8`

**Comment by matthewelwell** [comment]
[Related issue](https://github.com/Flagsmith/flagsmith/issues/2479)
