### ISSUE TITLE
Clone environment

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#172]
When creating a new environment, you currently take the default flag states for that project, which are currently not shown anywhere.

It would be better to be able to select which existing environment state you want to clone for the new environment.

**Comment by matthewelwell** [comment]
As discussed with @gagantrivedi:

We need an endpoint that 'clones' an environment. This should take the existing environment id and a new name for the cloned environment as an input and return the new environment details. Something like: 

```
POST /api/v1/environments/:id/clone

+ request

{
  "name": "<new environment name>"
}

+ Response

{
  "id": <new environment id>,
  "name": "<new environment name>",
  "project": {
    "id": <project id>,
    ...
  },
  "feature_states": [{...}]
}
```

**Comment by dabeeeenster** [comment]
@kyle-ssg I think we should add an Environment drop down here:

![image](https://user-images.githubusercontent.com/173290/127853772-10caebaf-d40e-4cda-be98-cc6e5980f165.png)

hook it up to the API, and then we're done.

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/pull/238 Frontend's done for this under the flag "clone_environment", just need backend.
![image](https://user-images.githubusercontent.com/8608314/127863697-cb089516-51c0-471f-b309-76e30030445f.png)

**Comment by dabeeeenster** [comment]
This isnt working for me on staging. 

1. Create new project
2. Create flag, default it to disabled.
3. Set flag as enabled in development env
4. Create new env, cloning dev env
5. New env has flag disabled. Expected it to be enabled.

**Comment by gagantrivedi** [comment]
The issue is the all the hooks installed on feature state are not aware of the cloning feature, and they fill the feature value with the default instead of using the cloned one.
One simple solution from  top of my mind is too add something like `source_env <fk to env>` that can be used(if not null) by the hooks to copy the value. @matthewelwell  what do you think?

**Comment by matthewelwell** [comment]
Yeah, that sounds like a smart idea to me.

**Comment by gagantrivedi** [comment]
> Yeah, that sounds like a smart idea to me.

This may work for Feature state, but we have to copy segments and identities as well. and some of them don't have hooks.

**Comment by matthewelwell** [comment]
Ok, so we just need to do that in the `clone` method on the environment I guess?

**Comment by gagantrivedi** [comment]
> Ok, so we just need to do that in the `clone` method on the environment I guess?

I am planning to implement clone method  on Feature state, feature segments and feature identity. each clone method will be responsible for creating clone of itself with a different env

**Comment by dabeeeenster** [comment]
Data to copy: 

- Feature States
- Segment Overrides

Make initiating user the Admin of that environment

Nothing else

**Comment by kyle-ssg** [comment]
As far as I can see, this still doesn't work - feature states are not copied over, at least currently in production. Also if it's behind a feature flag we should perhaps delay closing this until it's enabled.

**Comment by dabeeeenster** [comment]
Some data are not cloning correctly. E.g. I cloned this environment:

![image](https://user-images.githubusercontent.com/173290/129548730-bef8d5ad-0896-4b0f-a581-baf624cc2db5.png)

and this is what copied:

![image](https://user-images.githubusercontent.com/173290/129548765-8e0a93d9-93ed-4368-8397-e1524ac06c54.png)

Note the `background_colour` config value is different.

**Comment by gagantrivedi** [comment]
@dabeeeenster  can't reproduce. Can you list the steps?

**Comment by kyle-ssg** [comment]
Can no longer replicate, has this feature been deployed / adjusted in production since the 15th @gagantrivedi ?

**Comment by dabeeeenster** [comment]
Yep sorry I cant replicate this any more - closing
