### ISSUE TITLE
Filter Audit Log by Project

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#173]
Currently the audit log is showing logs for all projects within an Organisation. It should by default filter by project being viewed. 

I don't see any use-case for viewing logs by Organisation.

**Comment by gagantrivedi** [comment]
Looks like backend already supports filtering by project, we just need to pass the `project` in query params to make it work
e.g:
`localhost:8000/api/v1/audit/?project=1`

**Comment by dabeeeenster** [comment]
@kyle-ssg think you should have what you need to add this to the frontend

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/pull/213
