### ISSUE TITLE
Add "View Audit Log" to Project permissions

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#178]
Currently Project administrators cannot view audit logs for the project. They should be able to view an audit log filtered on the currently selected project.

**Comment by sw-tracker** [comment]
Hi @dabeeeenster ,

I have given these users project admin rights, but they still can't see the audit logs. I think currently, only org admins can view audit logs.

The idea would be, that users can view audit logs for which they have project admin rights.

Cheers,
Olga

**Comment by dabeeeenster** [comment]
Ah understood. Updated description - thanks!

**Comment by matthewelwell** [comment]
This one is tightly coupled to #173.

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/pull/215
