### ISSUE TITLE
App header is slightly broken in Firefox

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#180]
![image](https://user-images.githubusercontent.com/173290/125412785-21c4d480-e3b7-11eb-9c80-cbf22e5131f3.png)

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/pull/216

![image](https://user-images.githubusercontent.com/8608314/126819774-ed06b712-e567-4ea5-b664-d56abc50b0e6.png)
