### ISSUE TITLE
Unable to modify group permissions for projects or environments

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#182]
Clicking this button has no effect for me on Chrome 91 or latest Safari in OSX 11.4

![image](https://user-images.githubusercontent.com/173290/125479151-f25d9186-0597-4795-bb3b-cc4fb087c949.png)

**Comment by kyle-ssg** [comment]
You could, just click anywhere other than on the cog.

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/pull/217
