### ISSUE TITLE
Scheduling of Flag and Segment modifications

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#183]
*** This is an Epic needs splitting out into multiple stories ***

There are a number of use cases that are solved by having some form of timed automation of Flag and Segment modifications:

- Automating a rollout so that the % of users slowly increases over time, without manual intervention
- Enabling a feature based on some time based requirement, e.g. a marketing event
- Having a set process for rolling out features, e.g. first to internal team members, then 1 day later to beta tester, then roll out to user population over 3 days

## High Level Overview

Scheduled changes will leverage the versioning and change request work that we are implementing as part of #199 and #303 

Scheduled changes are effectively a list of Change Requests that go live at certain timestamps in the future. 

![image](https://user-images.githubusercontent.com/173290/159326695-8b8082cc-3c27-463b-b417-8a5cf81ff6a5.png)

**Comment by dabeeeenster** [comment]
This is a record of the original requirement/design which is superseded by the issue description.


*** This is an Epic needs splitting out into multiple stories ***

There are a number of use cases that are solved by having some form of timed automation of Flag and Segment modifications:

- Automating a rollout so that the % of users slowly increases over time, without manual intervention
- Enabling a feature based on some time based requirement, e.g. a marketing event
- Having a set process for rolling out features, e.g. first to internal team members, then 1 day later to beta tester, then roll out to user population over 3 days

## High Level Overview

Add two new domain objects:

1. Workflow
2. Workflow Stage

Workflows allow you to define a sequence of Stages based on particular timings. Workflows are defined first, and then associated to a Flag in the same way that Segments is. Workflow stages are similar to Segments in that they allow for flag states to be overridden based on the workflow. For example, a simple Workflow might be:

1. Set % split to be 5%, with flag state value set to `True`
2. 2 hours later, set % split to be 20%, with flag state value set to `True`
3. 2 hours later, set % split to be 100%, with flag state value set to `True`

## Workflow Details

Workflows are defined in a similar way to a collection of Segments. We will call these "Workflow Stages". These stages are similar to Segments but they have the following additional properties that need to be captured:

- Flag State Override Value (both boolean and config value)
- Time to wait from previous stage

## Scheduling the Workflow

Workflows are defined and then effectively a copy of the workflow is instantiated against a flag. Once the workflow has been defined, it can then be instantiated against a flag, either immediately or the Workflow instantiation can be scheduled to trigger at a particular time in the future. 

## Workflow Management

Workflows would be defined at a Project level.

**Comment by kyle-ssg** [comment]
Just realised this was closed as a result of my PR, we should create "workflows" as a separate ticket if there's still a usecase for them.
