### ISSUE TITLE
Unable to tap 'save' in portrait view on feature overlay on mobile

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#185]
![image](https://user-images.githubusercontent.com/173290/125642792-3833966f-49a0-42bc-8799-060d0a34b067.png)

Attempt to scroll, and nothing happens, was only able to save by rotating to landscape mode

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/pull/218
