### ISSUE TITLE
Usernames with '#' Break the UI

### ISSUE THREAD

**Issue by curtis-trynow-io** [Flagsmith/flagsmith#189]
If you create a user with a '#' character in the name, commonly used as a delimiter for text, no error is presented indicating that this is an illegal character.  The user will be created.  Upon attempting to interact with that user, you will be sent to a URL such as:

```
https://app.flagsmith.com/project/<ID>/environment/<ID>/users/test#user/<ID>
```

This results in a whitescreen with nothing rendered and then no way to end the condition unless you refresh the app.

A suggested fix would be to URL encode and decode the usernames along with any other user inputs that get appended to URLs.  You can reproduce this in any environment from what I can tell.

<img width="609" alt="Screen Shot 2021-07-16 at 1 39 58 PM" src="https://user-images.githubusercontent.com/87542480/125987767-d4926a87-8c8b-4022-a552-4d0056df6815.png">

**Comment by dabeeeenster** [comment]
Pretty sure this is related to the React router

**Comment by dabeeeenster** [comment]
This is still causing issues when trying to override flags for an identity

**Comment by dabeeeenster** [comment]
Hi @curtis-trynow-io can you test this against docker pull `flagsmith-frontend:main` - if you're happy with the fix we will go ahead and tag that commit. Thanks for the bug report!
