### ISSUE TITLE
Feature Leakage

### ISSUE THREAD

**Issue by rawkode** [Flagsmith/flagsmith#19]
When calling `getFeatures`, the API returns **ALL** feature flags. I'm proposing we should only return those flags which are enabled for the given user.

I don't see the point in "leaking" feature flags to an inquisitive user that otherwise doesn't need to know they exist :+1: 

Proposing the API would return this, instead of the latter:
```json
{
    "gt8_feature_flag_test": {
        "enabled": true,
        "value": null
    },
    "floating_action_button": {
        "enabled": true,
        "value": null
    },
    "oauth_google": {
        "enabled": true,
        "value": null
    },
    "interactive_tutorial": {
        "enabled": true,
        "value": null
    },
    "breadcrumbs": {
        "enabled": true,
        "value": null
    },
    "tasks": {
        "enabled": true,
        "value": null
    }
}

```

instead of:

```json
{
    "gt8_feature_flag_test": {
        "enabled": true,
        "value": null
    },
    "floating_action_button": {
        "enabled": true,
        "value": null
    },
    "oauth_google": {
        "enabled": true,
        "value": null
    },
    "test_remote": {
        "enabled": false,
        "value": "1"
    },
    "interactive_tutorial": {
        "enabled": true,
        "value": null
    },
    "breadcrumbs": {
        "enabled": true,
        "value": null
    },
    "thought_from_template": {
        "enabled": false,
        "value": null
    },
    "tasks": {
        "enabled": true,
        "value": null
    }
}
```

**Comment by dabeeeenster** [comment]
We've had a discussion about this and we're not sure hiding those disabled flags is the right approach. There will be cases where the default state for an app is having something enabled, and so the feature flag state being disabled would be relevant/required. 

We're not sure how we could get around this situation? I guess an option would be to add a second boolean ```hidden``` property to each flag that allowed you to prevent them from being sent back to clients?

**Comment by rawkode** [comment]
> We're not sure how we could get around this situation? I guess an option would be to add a second boolean hidden property to each flag that allowed you to prevent them from being sent back to clients?

Seems like a sensible solution to me :+1:

**Comment by dabeeeenster** [comment]
We now have the ability to hide disabled flags.
