### ISSUE TITLE
4 eyes principle for modifying flags

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#199]
This issue is dependent on #303 

## Overview 

Organisation Administrators should be able to specify individual Environments as requiring "4 eyes" (4E). This means that 2 people are needed to modify flags or segments within that Environment. This prevents features going live by mistake.

Anyone with read or write permission to a 4E enabled Environment can create Flag or Segment "Change Requests". Only people with write permission for the Environment can approve the request and execute the state change within that environment. 

### Set Environment as 4 eyes

In the Environment Settings page, Administrators should be able to mark the Environment as requiring 4 eyes approval for *all* flag changes. They can also set the number of approvals that are required up to a maximum of 5 approvals needed. 

### Stage Change Request 

The "Update Feature/Segment" button on Flag modifications for 4E environments should change to read "Create Change Request". 

![image](https://user-images.githubusercontent.com/173290/152017873-6e28e9a8-2c8e-48f9-b913-784a51e7a998.png)

### Create Change Request

Clicking the new button will take you to a "Create Change Request" Modal containing:

- Title
- Description
- Assign to (allow you to select many team members who have permission to approve the Change Request

![image](https://user-images.githubusercontent.com/173290/156144265-3f5040d3-c1a7-413e-b39e-9b1e37ea6f54.png)

### View Change Requests

A new navigation element should be shown for Environments that have 4 eyes enabled:

![image](https://user-images.githubusercontent.com/173290/152020136-c437ea42-9a93-4ead-8f8b-ef7574a5f0f9.png)

With the Title "Change Requests" and a badge showing the number of outstanding change requests that are queued. Clicking the link will take the user to a page showing the list of outstanding change requests. The UI would show details of each Change Request. If the user has permission to approve the change request, there is also an "Approve" button that will enact the change when submitted. 

## Permissions Model

- Only people with `Flag Write` permission for the environment should be able to create Change Requests. 
- Only people with `Flag Write` permission for the environment should be able to approve them.

## Issues

- Segments are defined at a Project level - how do we accomodate this aspect? 
  - _For now, lets just solve for Flags. Segments can come in v2._
- How do we deal with merge conflicts? 
  - _Last write wins._
- Do we allow multiple change requests per flag/segment? 
  - _Last write wins._
- How do we deal with behaviour being split between segments and flags? 
  - _For now, lets just solve for Flags. Segments can come in v2._ 

## API Changes

How to store Change Request states? This will hook into #303

**Comment by dabeeeenster** [comment]
Let's leave this as just for flags for now, not for segments.

**Comment by matthewelwell** [comment]
Some questions that came up when I was discussing the data model with @gagantrivedi earlier today:

 - Would we ever need to handle multiple change requests for a single feature state? Why?
 - Will all version changes need a change request or should it be possible to make a new version of a flag without a change request? I guess, as I'm writing this - that boils down to just directly editing the feature state? 🤔 Maybe it applies more to scheduled flags though. 

@dabeeeenster thoughts?

**Comment by dabeeeenster** [comment]
> Would we ever need to handle multiple change requests for a single feature state? Why?

We should allow multiple CRs against the same Feature State I think - last write wins

> Will all version changes need a change request or should it be possible to make a new version of a flag without a change request? 

Doing this gives us entire environment roll back options? or individual flag/env roll back? Plus audit log entries can point to specific versions. I don't really think there's much downside other than a trivial amount of disk space?

**Comment by matthewelwell** [comment]
> We should allow multiple CRs against the same Feature State I think - last write wins

But why? The thing is that it adds a certain level of complexity. Once one of the multiple CRs is committed what do we do with the others? Delete them? Update them to be a diff on top of the newly committed version?

> Doing this gives us entire environment roll back options? or individual flag/env roll back? Plus audit log entries can point to specific versions. I don't really think there's much downside other than a trivial amount of disk space?

I don't really think this answers the question tbh. You'd still get all of that without the change request wouldn't you? What you're suggesting is that every change to a feature state should contribute a new version which is fine. What I'm asking is whether we need the over head of a Change Request that needs to be given a title / approved etc. every time. Seems like unnecesssary overhead to me.

**Comment by dabeeeenster** [comment]
> But why? The thing is that it adds a certain level of complexity. Once one of the multiple CRs is committed what do we do with the others? Delete them? Update them to be a diff on top of the newly committed version?

Imagine a prod flag in a 4 eyes environment is scheduled to change state at a future date, say to go from 5% to 100% rollout. An issue comes up where the feature needs to be disabled. It still needs 4 eyes approval to be disabled. What happens now? You need to delete the original CR? Surely better to add a new CR that has immediate effect that disables the flag altogether? 

> I don't really think this answers the question tbh. You'd still get all of that without the change request wouldn't you? What you're suggesting is that every change to a feature state should contribute a new version which is fine. What I'm asking is whether we need the over head of a Change Request that needs to be given a title / approved etc. every time. Seems like unnecesssary overhead to me.

Ah ok - I think we should only create CRs when a user asks for them - generally they should not be used. Although I suppose if its a mandates 4 eyes environment, there would always be CRs for every state change.

**Comment by matthewelwell** [comment]
@dabeeeenster this is now available for testing on staging

A couple of things I've noticed: 
 * You can currently approve your own change requests - we should probably handle this FE and BE
 * We don't have any transactional email requesting a review from the assigned users

**Comment by dabeeeenster** [comment]
This time is wrong - shows current time, not created time 

![image](https://user-images.githubusercontent.com/173290/160709925-140eab38-45c4-496a-a675-dd7ad439e2e0.png)

Can we add a badge here with the number of outstanding CRs? 

![image](https://user-images.githubusercontent.com/173290/160710084-f682bca2-c277-4f47-8397-889c635078fe.png)

Toggles here don't trigger a change request

![image](https://user-images.githubusercontent.com/173290/160710247-93fb1c80-e6e3-4e3e-9554-d4b0d4a7736a.png)

Edit change request is blank

![image](https://user-images.githubusercontent.com/173290/160710376-b57131af-aa92-4c64-8349-769b5b801219.png)

Should be able to view closed CRs

![image](https://user-images.githubusercontent.com/173290/160710478-b3c37679-4c81-48e4-84b8-6c8113c0a8a7.png)

**Comment by dabeeeenster** [comment]
Some UI tweaks:

![image](https://user-images.githubusercontent.com/173290/160794325-910feb96-0e57-4791-ab7c-c5a80a11a55a.png)

![image](https://user-images.githubusercontent.com/173290/160794399-3b988141-54dd-471c-a34a-9af7f7e7062b.png)

**Comment by kyle-ssg** [comment]
I believe this can be closed after last tests 🚀
