### ISSUE TITLE
Segmentation

### ISSUE THREAD

**Issue by batjko** [Flagsmith/flagsmith#20]
Hi guys,

First of all, thanks for making the decision to go full open source on this project!

I saw in the docs that segments are a "Coming Soon" feature. It would be great to get some details on how that is planned to work (and if people can contribute ideas and perhaps help).

Will segments include the ability to segregate distribution by _any_ custom property?
Will random percentage be possible, for A/B testing?
Is it planned to make metrics available about the segmented distribution?

**Comment by dabeeeenster** [comment]
Hi @batjko  - thanks for the kind words. We've put up a couple of pages on the github wiki with regards to segments and integrations. We've also been working on user traits which I'm adding to the docs today. Maybe a discord channel would be helpful to chat?

**Comment by batjko** [comment]
Hi @dabeeeenster,

Checking in every now and then. I've seen the Wiki page for segmentation and it's a very good start, no doubt, but I think one massive use case is not yet mentioned:
Segregation by property, like a tenant.

Multi-tenancy is really important for most business applications, and being able to send a `tenantID` when registering a user/consumer in my app, and getting back a different value 
based on that ID, is something I would really really appreciate. 

And to be fair, other providers have that capability with various ways of defining context when registering the user.

So I'd like to be able to set a list of tenantIDs for my feature flag and say "If user-provided context field `tenantID` is one of these... then give it value X, otherwise value Y."

And this of course leads into controlling distribution, incl. percentage rollouts, A/B testing etc.

**Comment by dabeeeenster** [comment]
So I think you would be able to achieve this with traits and segments as currently designed. We recently added `Traits` to the API, allowing you to store key-value pairs along with `Identities`. So you could store a `tenantId` as a `Trait`. You could then create a segment called X with a rule like if tenantId in [55,76,124]. You would then be able to call identity.isInSegment('X'). 

Does this sounds feasible? Obviously the segments stuff doesn't exist yet, but would that accomplish what you need?

**Comment by batjko** [comment]
So, when the user logs in to an app, we register them with the BulletTrain server based on their authenticated context (which includes tenantID), by identifying them with the trait `tenantID: 123`, and then any `isEnabled()` call that targets that segment that this user is in (based on the given tenantIDs) would get back that enabled flag. 

If that's how this would work, then yes, absolutely 👍.

**Comment by dabeeeenster** [comment]
Yep - that's right. We're still defining the selection criteria for the rules so I guess we need to add lists of strings!

**Comment by kyle-ssg** [comment]
Work has started on Segments recently, we've gradually been rolling our WIP segment code into production using Bullet Train https://github.com/SolidStateGroup/bullet-train-frontend/blob/master/web/components/Aside.js#L136

Our rules engine for the JS client has been developed here https://github.com/SolidStateGroup/bullet-train-rules-engine. Basically, our clients will receive information on the segment rules and will figure out segmentation when it receives  user traits. This means changes to a segment's rules or a user's traits can have an immediate affect and we don't have to worry too much about scaling.

We're going to be rolling out the initial version to the JS client only then will start adding support for other clients.

**Comment by kyle-ssg** [comment]
Can be closed, segments have been in production for a while now
