### ISSUE TITLE
Add confirmation for identity overrides on the Flag override tab

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#208]
Clicking on the flag to change state for an Identity override should show a confirmation modal, reflecting the same workflow in the Identity page. 

![image](https://user-images.githubusercontent.com/173290/126659702-631b10d5-b3f7-4e56-a8d5-ed5c6f088a54.png)

**Comment by kyle-ssg** [comment]
Based on previous discussions around this and multivariate, clicking the user should now just navigate to that user in a new tab

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/pull/219
