### ISSUE TITLE
Calling "identify" with string containing a dot character does not respond correctly.

### ISSUE THREAD

**Issue by deividasm** [Flagsmith/flagsmith#21]
I am using js client and sending a string containing a dot.

`bulletTrain.identify("test.1");`

The response does not look right. The raw response payload is this string:

`Bullet Train API`

It works well if I use underscore instead of a dot for example:

`bulletTrain.identify("test_1");`

Then I get a proper JSON response.

**Comment by deividasm** [comment]
I have raised an issue in js client repo, initially thinking that it is a client issue. [https://github.com/SolidStateGroup/bullet-train-js-client/issues/5](https://github.com/SolidStateGroup/bullet-train-js-client/issues/5)

**Comment by matthewelwell** [comment]
Hi Deividas, this is now deployed. Please let us know if you experience any further issues.
