### ISSUE TITLE
Standardise tag selection

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#221]
It would be good to use the same UI for Audit log environment selection and flag tag selection.

IMO the Audit log UI looks better so we should copy that to the flag tagging UI

![image](https://user-images.githubusercontent.com/173290/126834543-bb822778-7ea2-4c6c-9f25-7eac08027bcc.png)

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/commit/3e7a0ea4b66397b45cfd80d097053455fb4d7571
