### ISSUE TITLE
Is there a way to just fetch a single feature from the API?

### ISSUE THREAD

**Issue by ryexley** [Flagsmith/flagsmith#222]
Whether via the JS SDK, or by going straight to the API, is there a way to just fetch a single feature/flag? I have a scenario where I would like to be able to just fetch a single feature to determine whether or not it is enabled, but I've not been able to figure out how to do that. We have a self-hosted instance, and have tried call `GET` to `/api/v1/flags/` followed by any number of different options after that, but every time we call that endpoint, it just returns _all_ of the flags for that environment. We've tried `/{id}/`, `/flags/?id=11`, etc, but nothing seems to work. Is there something we're missing?

**Comment by dabeeeenster** [comment]
No, that's not currently available at the moment. Can I ask what the use case is?

**Comment by ryexley** [comment]
(WOW that was a fast response, heh)

We're trying to define a feature flag to trigger "maintenance mode" in our app. The app is a react app, and we're initializing the flagsmith JS client, but feature data isn't being returned until _after_ we need to determine whether or not maintenance mode is enabled, so I was trying to figure out a way if I could just ping the API directly, and ask for the state of a single feature flag, to determine whether or not to redirect to our maintenance page, _as part of_ the application initialization process (before feature state is initialized).

I could just ping that endpoint and get _all_ of the flags, and then just filter on the one that we want ... but the (perhaps unreasonable) fear there was that as our list of feature flags grows, the response payload of that call could get quite large for the sake of just wanting the information or state of a single feature.

**Comment by dabeeeenster** [comment]
Ah ok understood. Generally we wouldn't recommend having so many flags that the payload data of the full set of flags is so large you need to be worrying about its size over the network. Having to make 2 sequential requests would probably be worse? 

If you really wanted to do that you could make another project with just a single flag? 

Funnily enough in 3 years this is the first time this has come up (that I can remember, anyway).

**Comment by ryexley** [comment]
I agree, and that's not likely to happen, but we'll see. I will probably end up going the route that I mentioned above where I just fetch them all and filter on the one that I'm specifically interested in ... it's a fairly small edge case scenario anyway.

Thanks!
