### ISSUE TITLE
Database idle connection

### ISSUE THREAD

**Issue by Dionizioaf** [Flagsmith/flagsmith#223]
I deployed flagsmith in AWS EKS with RDS Postgre

Im using 4 replicas of API and 1 replica of any other POD.

In the dabase iḿ using 
- 6% of 2vcore processor
- 1.5GB of 4GB of memory

--
We are having a problem with the idle connection in the database. The sum of connection keeps growing until my database crashes. 
In the graph every time the sum of connection drops is because i restart all 4 flagsmith api pods

![image](https://user-images.githubusercontent.com/5961020/126850250-42399659-f3d2-4f9c-b1b7-cf63a554fce3.png)

In the begging i imagine that it was my devices connecting to flagsmith, but when i check the session info of the database, i see that some connection was idle for a lot of time.

The process selected in the image was connect 26 minutes ago.

![image](https://user-images.githubusercontent.com/5961020/126850398-f329bf9c-cd00-493a-aea0-98282d4bcc6b.png)

I try to limit the number of connection to check if the app recycle the pool, but when the server reaches the limit it start to reply error 500.

 In many documentations is suggested that the connection don't remain in idle state in the database, and for me there other problem because, i increase my RDS for the third time just to get more connection slots. 

So, my question is, is there a way to configure flagsmith so it don't remain connected in idle state?

**Comment by dabeeeenster** [comment]
Hi. Can you detail the RDS instance. Size and max number of connections?

**Comment by Dionizioaf** [comment]
AWS RDS Postgre db.t2.medium
2 vcpu 3.3
4GB of memory

database connection limit is 350

I have a Redis in front of Flagsmith with 10 minutes cache.

In Flagsmith i configured cache_flag_seconds and cache_project_segments_seconds both with 300 (I was having doubts where to configure so i created a flag and in the API YAML env.)

In the moment i really dont know how many devices is using flagsmith, but probably hundreds. The devices is making a connection every time the app is open and every 10 minutes, so i really have a lot of concurrent connection. 

For example after midnight yesterday the connection number drop alot.

**Database Stats**
![image](https://user-images.githubusercontent.com/5961020/126876577-e17292d2-2f3a-46c4-94d1-5be07ff07ec8.png)
Before 6PM yesterday i had a 200 connection limit in the database.


**EKS Stats**

![image](https://user-images.githubusercontent.com/5961020/126876879-b8b291f2-3e83-496f-944c-11eca37a5141.png)

**Comment by Dionizioaf** [comment]
I deploy a pgbouncer to controller the database connection, i went from 350 connection to 4 concurrent connections.

Im closing the issue

**Comment by dabeeeenster** [comment]
@gagantrivedi can we add an env var called `DJANGO_DB_CONN_MAX_AGE` to common.py, default to 60 and update docs. Users should be able to manage this variable as it controls database session lengths

**Comment by Dionizioaf** [comment]
I Will try that, thanks
