### ISSUE TITLE
Unable to filter user lists

### ISSUE THREAD

**Issue by DanHammond** [Flagsmith/flagsmith#225]
For the last few days I have been unable to filter neither the user list, or the user dropdown from the identity overrides section

On the user list, it will type in 1 character, but then this gets cleared before I can type the next character

I can see a request going out

https://api.flagsmith.com/api/v1/environments/gpjCB9cLrFxKj26vcKVh9S/identities/?q=t&page_size=10

but as I type more it still sends the same request without the full filter string

**Comment by dabeeeenster** [comment]
Reproduced in production.

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/pull/226
