### ISSUE TITLE
docker-compose up does not work.

### ISSUE THREAD

**Issue by holmok** [Flagsmith/flagsmith#23]
When I run `docker-compose up`, after I cloned the repo, from the repo's root directory. I get the following:

```
... [build logs / postgres starting] ...
api_1  | python: can't open file 'manage.py': [Errno 2] No such file or directory
bullet-train-api_api_1 exited with code 2
```

My docker-compose version is: 
```
$ docker-compose --version
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

and docker:

```
$ docker --version
Docker version 18.09.2, build 6247962
```

I am also running on a mac using Docker Desktop

**Comment by matthewelwell** [comment]
Hi @holmok, thanks for bring this to our attention. I've just merged a fix in to resolve this, let me know if you experience any further issues.

**Comment by holmok** [comment]
Looks good thanks!
