### ISSUE TITLE
Google Sign-in JS Deprecation Warning

### ISSUE THREAD

**Issue by curtis-trynow-io** [Flagsmith/flagsmith#259]
We use Google for SSO with Flagsmith and have a client app configured for authentication.  We received an email yesterday from GCP informing us that one of the libraries Flagsmith is using has been deprecated.  Following the link out to their announcement leads to https://developers.googleblog.com/2021/08/gsi-jsweb-deprecation.html.

I was not able to find an actual call to `apis.google.com/js/platform.js` as the post mentions, but this is the only client app we received this email notice for.  I am attaching a screenshot of the email with the client app ID redacted for reference.
<img width="1224" alt="Screen Shot 2021-08-12 at 1 54 03 PM" src="https://user-images.githubusercontent.com/87542480/129245638-1b6ef3b1-43e8-4d7c-89da-112e91c7d4c3.png">

**Comment by dabeeeenster** [comment]
OK this needs sorting before 2023 😄  but we should try and just get it done if its a simple code replacement.

**Comment by curtis-trynow-io** [comment]
I fully expected this to be triaged and put somewhere way far out on a roadmap, no urgency at all.

**Comment by kyle-ssg** [comment]
I believe the above should resolve this, let me know if not 😃 .
