### ISSUE TITLE
Move "Toggle All" link

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#276]
In the screenshot below, its a bit ambiguous that the "Toggle All" copy that relates to the tags might related to the flags.

![image](https://user-images.githubusercontent.com/173290/130048646-87701316-7efc-48ab-a974-daff7c74ac29.png)

I think putting the tags filter in a drop down might be better and clean the main features page up? Similar to how Github Issues filter. 

![image](https://user-images.githubusercontent.com/173290/130048819-8d5dc89d-8115-4af0-a5aa-87b3ee902c7e.png)

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/pull/363
