### ISSUE TITLE
Knowing when a feature flag isn't used anymore

### ISSUE THREAD

**Issue by fclairamb** [Flagsmith/flagsmith#28]
It would be interesting to store when a feature flag was last read (with a few hours approximation would be fine) so that we can know we can actually remove it.

**Comment by dabeeeenster** [comment]
Thanks for the suggestion, Florent. I guess a good way to implement this would be to cache which flags have been read and only write them to the database every X minutes to avoid overloading the DB with unnecessary writes. 

Happy to accept a pull request!

**Comment by fclairamb** [comment]
Yep and there's an even simpler way to do that it's the [relatime](https://blog.confirm.ch/mount-options-atime-vs-relatime/) way: You write the change once the last access date is more than X minutes before now.

**Comment by nischithbm** [comment]
> Knowing when a feature flag isn't used anymore

This would be totally useful!

Also feature flag aging reports/alerts would helpful as well.
For notifying owners to remove them after X number of days (lets say 90 days).

**Comment by dabeeeenster** [comment]
The issue we have here is that most of this work is on the client side SDKs. 

I guess if the SDKs only sent updates every 5 minutes or so, based on a relatime algorithm. 

There would also be complications regarding server side SDK implementations. What if you have a fleet of 50 app servers? Do they each send a relatime update or do they have some sort of shared state? The SDK wouldn't know about any of that detail. 

I've added it to our backlog.

**Comment by dabeeeenster** [comment]
This is being developed now - we hope to have flag analytics released before the end of 2020.

**Comment by dabeeeenster** [comment]
If anyone wants to beta test this feature, please let me know!

**Comment by dabeeeenster** [comment]
This is now in beta - shout if you want access!
