### ISSUE TITLE
Environment permissions screen should show if a user is a project admin

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#289]
If a regular user account is made a project administrator:

![image](https://user-images.githubusercontent.com/173290/131975763-da48fbaa-47f3-47ea-90cc-bf583c31adad.png)

They should show as a project admin on the environment permissions screen:

![image](https://user-images.githubusercontent.com/173290/131975883-1e660d0f-4160-4633-85ce-3864bc9452ef.png)

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/pull/364
