### ISSUE TITLE
Add additional meta data to Identities

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#290]
Use case:

> Wondering if there's a way we can add something like notes or tags to identities in the Flagsmith UI that are not accessible via the non-secret environment key. The use case is that we want to be able to add actual customer names to identities so it's easier to toggle flags per customer, but we of course want it to be impossible to get that info via the env key. 

So these would need to be indexed and searchable as well.

**Comment by kyle-ssg** [comment]
Needs fleshing out, assign to me when we've got a bit more of a spec.

**Comment by matthewelwell** [comment]
Closed accidentally after being linked to an incorrect PR.

**Comment by matthewelwell** [comment]
Superseded by #4016
