### ISSUE TITLE
Add an option to disable UI on docker

### ISSUE THREAD

**Issue by gnumoreno** [Flagsmith/flagsmith#2903]
**Is your feature request related to a problem? Please describe.**
Currently the docker image deploys both UI and API. It would be nice to have an option to disable UI.

**Describe the solution you'd like**
Add an option to entry point to disable UI

**Describe alternatives you've considered**
Having a separate image with API only

**Additional context**
Apparently it is a somewhat common use case.

**Comment by dabeeeenster** [comment]
Not sure the best way of achieving this - maybe just disable the dashboard routes in Django?

**Comment by matthewelwell** [comment]
Resolved in #3097
