### ISSUE TITLE
Refactor Frontend Env Var names

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#296]
Some of the environment variable names for the Front End are a bit ambiguous. We should rename these and deprecate support for the old variable names. Suggested new names are below:

- API_URL > FLAGSMITH_API_URL
- FLAGSMITH > FLAGSMITH_ON_FLAGSMITH_API_KEY
- FLAGSMITH_CLIENT_API > FLAGSMITH_ON_FLAGSMITH_API_URL
- DISABLE_INFLUXDB_FEATURES > ENABLE_INFLUXDB_FEATURES (and ! value, defaults to true)
- FLAGSMITH_ANALYTICS > ENABLE_FLAG_EVALUATION_ANALYTICS (defaults to true)
- PROXY_API_URL > PROXY_API_URL
- GA > GOOGLE_ANALYTICS_API_KEY
- CRISP_CHAT > CRISP_WEBSITE_ID
- PREVENT_SIGNUP > ALLOW_SIGNUPS (defaults to `true`)
- MAINTENANCE > ENABLE_MAINTENANCE_MODE (defaults to `false`)
- AMPLITUDE > AMPLITUDE_API_KEY
- MIXPANEL > MIXPANEL_API_KEY
- SENTRY > SENTRY_API_KEY
- ASSET_URL > STATIC_ASSET_CDN_URL
- BASENAME > BASE_URL

For running the Front end as part of the existing API docker image, I plan on just using the new names agreed on here. For the stand alone front end docker image, I plan on taking the new names in the first instance but falling back to the old names if new names are not present. This will prevent existing FE docker image runtimes from breaking.

**Comment by dabeeeenster** [comment]
Would like some feedback on these. Tried to follow the same patterns as the API keys

**Comment by kyle-ssg** [comment]
These make sense, but perhaps:
- CRISP_CHAT_WIDGET_API_KEY: may be a bit long winded, CRISP_WEBSITE_ID is what they call it, so perhaps we should use that
- BASENAME: I don't think this is used anywhere anymore so we can remove
- ASSET_URL: I don't see any danger in keeping this, it speeds up things currently in production for us. So long as the default value works, we don't have to document it if we don't think it'll be used often. If this isn't currently working as empty in the docker image it seems like defaulting to "http://localhost:"+process.env.PORT||8080 would work
- PROXY_API_URL: Following the above should maybe be FLAGSMITH_PROXY_API_URL

**Comment by dabeeeenster** [comment]
FLAGSMITH_ON_FLAGSMITH_API_URL has been removed?
