### ISSUE TITLE
Allow seamless in-app seats upgrades

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#298]
# For Startup SaaS

Users should not be able to add additional seats. If attempting to invite a user or visit an invite link, they should be told that they need to upgrade to Scale Up. 

# For Scale Up SaaS

Customers should be charged for additional seats as they use them. 

There are different ways seats can be added (invite links being used, or invite emails sent out to specific email addresses). 

Whenever a new user registers, we need to amend the `Additional Seat` Add On in chargebee and set it to the correct number for the account. This will then trigger an email to the Chargebee registered email address with the change. 

# Chargebee Implementation

https://support.chargebee.com/support/solutions/articles/223536-how-do-i-remove-change-add-an-addon-to-a-subscription-that-already-has-one-or-more-addon-via-apis-

> While using the [Update a Subscription API](https://apidocs.chargebee.com/docs/api/subscriptions#update_a_subscription), by default, the addons passed are appended to the existing list of addons for a subscription. In case a passed addon already exists for this subscription, quantity value is replaced. If you want to completely replace the addons for a subscription, pass replace_addon_list as "true".

https://apidocs.chargebee.com/docs/api/subscriptions?prod_cat_ver=1#update_a_subscription

- The add-on we need to modify has the id `additional-team-members-scale-up-v2-monthly`
- Set `prorate` to `true`
- Set `invoice_immediately` to `true`

**Comment by gagantrivedi** [comment]
The backend already supports this. front-end just needs to add update subscription modal on the front-end.

**Comment by kyle-ssg** [comment]
@dabeeeenster shouldn't this just automatically happen when inviting a user? I think that's pretty standard e.g. vercel

**Comment by dabeeeenster** [comment]
Yes but we need to have a think about who has authority to charge the card we have on file. ATM more than just org admins can invite new users, no?

**Comment by kyle-ssg** [comment]
No, only org admins can invite

**Comment by gagantrivedi** [comment]
What about free plans?

**Comment by dabeeeenster** [comment]
Free plans should be locked to a single seat and require at least a Start Up plan. We should not show the invite link if they are on a free plan and direct the user to the upgrade modal.
