### ISSUE TITLE
A modal shouldn't open when you don't have UPDATE_FEATURE_STATE permission

### ISSUE THREAD

**Issue by novakzaballa** [Flagsmith/flagsmith#2988]
**Describe the bug**

In the backend, If you don't have UPDATE_FEATURE_STATE you can't update the feature, but in the UI, You haven't any feedback that you can't update the feature.

**To Reproduce**

Have a user who does not have the UPDATE_FEATURE_STATE permission
1. Go to the Identities page.
2. Select an Identity
3. Click the feature switch 
4. A confirmation modal opens to change the value of the feature

**Expected behavior**

The feature switch should not be clickable or a message should appear saying "you do not have permission to do this"

**Screenshots**

<img width="828" alt="Screen Shot 2023-11-16 at 13 39 28" src="https://github.com/Flagsmith/flagsmith/assets/41410593/89bed61d-2700-410f-9c11-158b40c1afe9">

**How are you running Flagsmith?**

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [x] Some other way

**Comment by kyle-ssg** [comment]
Looking through this, I cannot replicate and the code looks correct 

![image](https://github.com/Flagsmith/flagsmith/assets/8608314/b3453afd-968d-4df5-a4fa-43bfe62faa5f)
