### ISSUE TITLE
Allow customers to sign up with an Annual payment option

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#299]
10% discount for Annual up front credit card payments.

**Comment by kyle-ssg** [comment]
@dabeeeenster could we set up a chargebee subscription type to progress this? Even if it's just on staging

I'll be able to update paywall / the payment modal from this

**Comment by dabeeeenster** [comment]
OK staging and prod now have new plan ids:

- `startup-annual-v2`
- `scale-up-annual-v2`

**Comment by kyle-ssg** [comment]
Awesome thanks

**Comment by kyle-ssg** [comment]
This is done and live under the feature flag "annual_plans".

A couple things to note:

- It looks like upgrades don't work on staging, if you spot this it was still the case before this change
- The pricing for annual is static, would need changing
- We'd also need to update the home page
