### ISSUE TITLE
Forbidden (CSRF cookie not set.): /auth/login/

### ISSUE THREAD

**Issue by lukaskarol** [Flagsmith/flagsmith#32]
I run Api locally, set up Postgres database localy and run fronted API also locally.

I have communication between fronted and api but every request throw
"Forbidden (CSRF cookie not set.): /auth/login/" 
and i don't know if i miss something and i have wrong configuration or i need to add something into the code?

**Comment by kaue-eufrosino-movile** [comment]
Hey, I'm facing that issue too, do you guys have a solution?

**Comment by matthewelwell** [comment]
Hi @lukaskarol, I appreciate it's a been a while since you raised this but I'm responding here in case you or others are still having this issue. 

From the output you posted in the comment above, it looks as though you are attempting to run the backend (and probably the frontend) on a windows machine (Basing this on the message 'Quit the server with CTRL-BREAK'). 

The application has not been tested running on a windows machine and we're not likely to support that any time soon. For anyone running on Windows, I suggest that you use our Docker setup instead.

**Comment by jogoncalves** [comment]
I'm facing the same issue. 
I'm running both api and frontend with docker and even though i have the csrftoken cookie, it seems to not be passed onto the api.
Like @lukaskarol I get "Forbidden (CSRF cookie not set.): /auth/login/". 
Did you ever solve this?

**Comment by dabeeeenster** [comment]
Can you guys try the docker compose file? https://github.com/BulletTrainHQ/bullet-train-docker

**Comment by d3rf** [comment]
Im trying to create a feature using REST API, so I ve launched the docker image using 
docker-compose -f flagsmith/docker/docker-compose.yml up
then
FRONT END is running in 8080
API is running in 8000

So, I ve create a nodejs to authenticate using API 
```
const axios  = require('axios').default;
axios.post('http://127.0.0.1:8000/api/v1/auth/login',{
        "email": "frederico.fiuza@*********",
        "password": "mysecret"
 }).then((response)=>{
     console.log(response);
 }).catch((err)=> {    
     //console.info(err.toJSON())
    console.log(err.response)
     
});

```

And always answer with 403 CSRF Token

**Comment by dabeeeenster** [comment]
How are you creating the `frederico.fiuza@*********` account?

**Comment by d3rf** [comment]
> How are you creating the `frederico.fiuza@*********` account?

Running docker local, then accessing frontend and signup.
If I run curl command the key is generated successfully, If I use a nodejs axios DJANGO REST complains about CSRF

**Comment by kyle-ssg** [comment]
I believe this is simply due to missing a "/" after login, django endpoints are sensitive to this and throw the above error when missed.

Try http://127.0.0.1:8000/api/v1/auth/login/
