### ISSUE TITLE
support for realtime updates

### ISSUE THREAD

**Issue by sahanatroam** [Flagsmith/flagsmith#38]
Will there be plan to expose realtime updates ? Maybe utilise socket.io so that when the values are updated there would be an event that gets dispatched to the clients in realtime ? 

This would avoid the clients having to short poll the backend to fetch the latest updates.

CC @matthewelwell @dabeeeenster

**Comment by dabeeeenster** [comment]
Hi @sahanatroam ,

We've considered it, yes. The issue really is the amount of resources required for apps that generate any sort of significant levels of traffic. If you're running an app with say 100k active users you would need a fairly large fleet of web-socket servers just to serve those connections. And then the only benefit you are getting is immediate updates based on flag changes; in our experience flag changes happen relatively infrequently. So you're running a LOT of infrastructure overhead and complexity for relatively little end user/product gain. Do you *really* need flag updates to reflect immediately on your end clients?

If you have an app with a strong real-time data requirement, you will almost certainly already be running some sort of websocket/serverside event setup. Our solution in this situation is to use our [WebHooks](https://docs.bullet-train.io/system-administration/#web-hooks) to send flag changes to one of your own backend servers. You can then use your own real-time infrastructure to deliver those flag updates to your clients. 

Would like to hear your opinions on that! Also if I could ask what your use case is for requiring immediate flag updates on your clients?

**Comment by sahanatroam** [comment]
Hi @dabeeeenster 

Thanks very much for your answer.
There is no actual usecase as of now. 
We're currently trying to find an alternative to Firebase Remote config, as we're finding the throttling an issue.

Great that you pointed out the webhooks feature. I will present this to the team and come back to you on how we get on :) 

Thanks again for the extensive answer.
