### ISSUE TITLE
PHP Support

### ISSUE THREAD

**Issue by grafikkaos** [Flagsmith/flagsmith#40]
Hi there,

Just a quick question, will there be support for using PHP at some point.  So far, there only seems to be .NET or JAVA in terms of server side languages and PHP is missing.

Thanks,

Emmanuel

**Comment by dabeeeenster** [comment]
Hi,

It's in the backlog - we're happy to take pull requests tho!

**Comment by dabeeeenster** [comment]
Implemented here: https://github.com/BulletTrainHQ/bullet-train-php-client
