### ISSUE TITLE
"Save" button in modals is never re-enabled in case of failure

### ISSUE THREAD

**Issue by rolodato** [Flagsmith/flagsmith#4026]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [X] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

When saving changes within a modal (i.e. feature states, segments, segment overrides, possibly others), the Save button is disabled while requests are still pending. However, if a request fails, the button is never re-enabled and requires a page reload to be clickable again. This effectively means losing all your UI state, which can be very frustrating.

### Steps To Reproduce

See video below.

1. Force a request initiated by saving within a modal to fail somehow. For example, manually block a request needed to save a feature using developer tools:

![image](https://github.com/Flagsmith/flagsmith/assets/829698/aacd6eb4-fad3-446d-a95d-8681ebb64d9c)

2. Save a feature, forcing a request to be blocked
3. The Save button is never re-enabled and requires a full page reload to work again

### Expected behavior

Saving within modals should have proper error handling and eventually always re-enable the Save button.

The error message should be displayed to the user, requiring manual dismissing to allow time to copy/paste or screenshot the error.

### Screenshots

https://github.com/Flagsmith/flagsmith/assets/829698/a352a287-ed4f-4ac7-a989-bef9122a6fa6

**Comment by rolodato** [comment]
Even easier way to reproduce this issue: try to create a feature with a duplicated name.

**Comment by kyle-ssg** [comment]
Just to clarify, I think you're just meaning within the feature modal?

**Comment by rolodato** [comment]
@kyle-ssg Yes that's correct, I thought I had reproduced it elsewhere but it's only in the feature modal.
