### ISSUE TITLE
Toggle all tags button is not visible in a Dark theme

### ISSUE THREAD

**Issue by milanjaros** [Flagsmith/flagsmith#414]
Tags have a white background in a Dark theme, so the Toggle all tags button is not visible. 
![tags.png](https://user-images.githubusercontent.com/455194/137340901-0ee8713d-7e10-4b58-b670-94f6ce46bdd0.png)
Expected result:
![tags-expected.png](https://user-images.githubusercontent.com/455194/137341282-2b05f3b9-00d4-427e-9787-53834ee85dc8.png)

I can see there is an inline style defining light background:
![style.png](https://user-images.githubusercontent.com/455194/137341091-825f1fce-9446-4b88-a648-fff1383e3806.png)

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/pull/433
