### ISSUE TITLE
Clicking toggle on an Identity override takes you to Identity page instead of activating toggle

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#417]
![image](https://user-images.githubusercontent.com/173290/137687486-f06e27ea-6870-4b93-b304-0bba50c0777f.png)

Clicking the toggle no longer works.

**Comment by kyle-ssg** [comment]
Discussing internally, will replace with something more like 
![image](https://user-images.githubusercontent.com/8608314/137709822-5f5ef498-bf42-4b96-8e73-ddd2a4283d15.png)

Clicking edit opens the feature modal in the user page

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/pull/433
