### ISSUE TITLE
pipeline for building

### ISSUE THREAD

**Issue by euprogramador** [Flagsmith/flagsmith#42]
create pipeline for build production and release docker image for distribution

**Comment by euprogramador** [comment]
CicleCi or Github Actions or Travis CI ?

**Comment by dabeeeenster** [comment]
We've set up Docker Hub builds for this. The builds are available here: 

https://hub.docker.com/repository/docker/bullettrain/api

https://hub.docker.com/repository/docker/bullettrain/frontend
