### ISSUE TITLE
"Toggle All" on flags list doesnt update list

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#426]
Clicking Toggle All doesnt effect any updates in the flag list:

![image](https://user-images.githubusercontent.com/173290/138078376-027fde15-bbe0-4b4b-aa87-4b4df1d5b76c.png)

**Comment by kyle-ssg** [comment]
It does, please reopen with replication steps. Having no tags selected acts the same as having all selected by design to essentially replicate having no filters, upon selecting 1 or more tags or archived filters down results.

<img src="https://recordit.co/Bx5Q8JdaYW.gif"/>
