### ISSUE TITLE
Modify self hosted RBAC copy to detail closed source component

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#428]
Currently if you run the platform with Docker-compose you get the following message:

> Please upgrade your account to enable role based access.

This copy should be changed when self hosting to read:

> Role-based access is not available in our Open Source version. Please contact sales@flagsmith.com for more information on our licensing options.

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/pull/433
