### ISSUE TITLE
Need help: High level design/architecture

### ISSUE THREAD

**Issue by nischithbm** [Flagsmith/flagsmith#45]
This project looks really interesting, and I tried setting up this locally as well - works like a charm. 
However, I am interested to know more about the underlying architecture. Does it handle realtime updates across clients, etc.

Is there a documentation which covers high level architecture? And any developer documentation. I see a lot of documentation is available for consumer of this infra. It would be good to have a place for developer/contributor documentation to enable more developers to contribute.

Overall, great initiative!

**Comment by dabeeeenster** [comment]
Hi,

Thanks for the kind words! We don't support real time updates natively, no. It is on the road map but we don't have it as an urgent feature right now. 

Regarding developer documentation, what sort of thing are you looking for? I'd be happy to add more to https://docs.bullet-train.io/ but I'm not sure what sort of thing you're after?

**Comment by nischithbm** [comment]
I am looking to consume & contribute. But before getting into it, I am evaluating existing open source implementations. So if you could share a high level architecture of the entire system, that would be really awesome. Mostly to understand the internals (not just the features or capabilities) - Hope this clarifies?

I believe, this would encourage more developers to contribute to the core infra itself.

**Comment by dabeeeenster** [comment]
Ive added a basic architecture document here: https://docs.bullet-train.io/architecture/

**Comment by nischithbm** [comment]
Thanks @dabeeeenster for adding the high level architecture. This is definitely a great starting point, whenever you get a chance if you could add low level design specifically covering the internals of the core API - that will be awesome.

![image](https://user-images.githubusercontent.com/1619263/86512170-34f4aa00-be1d-11ea-8090-aa47dd7e0c3e.png)

**Comment by dabeeeenster** [comment]
The API is Django and Django Rest Framework - LOADS of info about that here! https://github.com/BulletTrainHQ/bullet-train-api
