### ISSUE TITLE
Handle special characters in database URI

### ISSUE THREAD

**Issue by harenlewis** [Flagsmith/flagsmith#47]
Hi, while setting up the custom database, I came across this issue where my db uri had an `#` in the password and it was failing with the following error: 

```
>>> dj_database_url.parse('postgres://root:test#123@127.0.0.1:5432/test_db', conn_max_age=60)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/harenlewis/Projects/ff_env/lib/python3.6/site-packages/dj_database_url.py", line 105, in parse
    port = (str(url.port) if url.port and engine == SCHEMES['oracle']
  File "/usr/lib/python3.6/urllib/parse.py", line 169, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'test'
```
On digging a little it looks like it how `dj-database-url parses url`!
You can read more about it here: https://github.com/jacobian/dj-database-url/issues/39

I've worked on resolving this, will submit a PR soon!

**Comment by dabeeeenster** [comment]
Hey thanks so much for the issue and PR. I think it would be cleaner to submit a PR to the `dj-database-url` repo? I'd rather do that than try and patch our code?

**Comment by harenlewis** [comment]
Yes, seems that is the correct way. Looking at the `dj-database-url` repo, it looks like it's not been updated for the last 7 months. In that case, how do you suggest we get it working if there are special characters in DB URI?
Also, I need to confirm if it's only limited to **`#`** character, then avoiding **`#`** char can be a possible thing.
