### ISSUE TITLE
Static CSS files for administration interface seem to be missing

### ISSUE THREAD

**Issue by andrewshawcare** [Flagsmith/flagsmith#51]
Not sure if this is because the `static` folder is ignored in `.gitignore`, but when logging into the Django adminstration interface, there is no styling applied and the CSS files are not located (the server responds with the, "Bullet Train API" page).

I'm attempting to run the API via Docker (this may or may not be relevant to the issue as I haven't tried running outside of Docker).

**Comment by dabeeeenster** [comment]
Hi @andrewshawcare - can you provide details of how you're running the docker app? We've made some changes around this recently so its possible that the static folder is not being built via docker...

**Comment by andrewshawcare** [comment]
#52

**Comment by andrewshawcare** [comment]
I think it was missing the `collectstatic` command. I'm new to Django, so not entirely sure but that generates the appropriate CSS files after adding to the `docker` script in the `bin` folder.

**Comment by andrewshawcare** [comment]
Added another PR for the development container: #53
