### ISSUE TITLE
Project is required in body for feature update despite being included in path

### ISSUE THREAD

**Issue by andrewshawcare** [Flagsmith/flagsmith#55]
### Steps to reproduce

Make a request to update a feature, like so:

```
PUT /api/v1/projects/2/features/7/

{...}
```

### Expected behaviour

Feature for the project is updated

### Actual behaviour

`400` error received:

```
{"project":["This field is required."]}
```

**Comment by andrewshawcare** [comment]
This can also be reproduced using the frontend UI docker image (it's how the bug was found originally).

**Comment by dabeeeenster** [comment]
Hi Andrew,

Thanks for this report - we're on it! Will have a fix ASAP.
