### ISSUE TITLE
Have /api/v1/users/init/ return a JSON response or an empty body

### ISSUE THREAD

**Issue by andrewshawcare** [Flagsmith/flagsmith#59]
I've created a provisioning script and a client wrapper for the Bullet Train API which throws an exception when attempting to parse the response from `/api/v1/users/init/` as it seems to only return a text body of, "ADMIN USER CREATED".

Ideally, when the `Accept` header is set to `application/json`, the API could return either a `201 Created` response with no body or the same message as a JSON payload:

```
{
  "adminUserCreated": true
}
```

**Comment by dabeeeenster** [comment]
Hi Andrew,

Thanks for this - It's on the backlog and will get fixed up shortly.

**Comment by tushar5526** [comment]
I would like to work on this if this is not solved internally :)

**Comment by dabeeeenster** [comment]
Yep that would be great @tushar5526
