### ISSUE TITLE
List all /identities/ and filter by trait

### ISSUE THREAD

**Issue by wasabigeek** [Flagsmith/flagsmith#62]
The use case for us is to handle subsets of data differently for a group of identities (e.g. for internal tools) while we're rolling out features. Our current workaround is to create a Segment and assign multiple OR conditions (e.g. id=1 OR id=2), then retrieve that Segment and naively transform it into a list.

Would be open to contributing, any particular reason why the identities doesn't have an option to list all / isn't a ModelViewSet? https://github.com/BulletTrainHQ/bullet-train-api/blob/master/src/environments/views.py#L390. The `get_or_create` also seems a little unusual.

**Comment by matthewelwell** [comment]
Hey @wasabigeek. I'm not entirely sure what you mean when you say 'filter by trait_id' do you mean by `trait_key`?  

Regarding why the SDKIdentities view class doesn't use a ModelViewSet, the short answer is that, well, it was unnecessary at the time. It's worth noting that this endpoint is only used by the SDKs, not by the admin interface (where we do have the option to list identities for an environment).

I'd be interested to understand a little more about why the segments functionality doesn't quite handle your use case, have you checked out the regex operator perhaps? In what scenario would you need to return multiple identities?

**Comment by wasabigeek** [comment]
Thanks for the response @matthewelwell! My bad, not filter by trait key, but by a combination of trait and value.

We want to retrieve the list of users that have a certain trait value from BulletTrain. The internal user_id is a trait which we’ll then retrieve from those users.

Something like this:
```python
enabled_users = # filter users from bullet train that have trait == value
User.objects.filter(id__in=enabled_users)
```
(I haven’t used Django in a while, hope that was correct)

**Comment by matthewelwell** [comment]
Interesting, and this list of users, are you trying to obtain that for some processing outside of the bullet train functionality? Or are you trying to show / hide a feature based on this information? If it's the latter, I think segments should work for your use case by just using another trait but perhaps I'm misunderstanding here. 

Sorry if I'm asking too many questions, I'm just trying to understand the use case a little more.

**Comment by wasabigeek** [comment]
> are you trying to obtain that for some processing outside of the bullet train functionality? 

The former, though I'm not too sure what you mean by "outside of the bullet train functionality".

I'll try to illustrate (not exactly our use case):
- each **BT user** has a trait `user_id` which maps to a **User** in our SaaS
- we're progressively rolling out an upcoming change that will affect both user-facing features and background processing across users, and were hoping to setup BT as such:
  - Users that we want to rollout to will have a trait e.g. `show_new_changes`
  - These Users will then be in a **BT Segment**, via a rule `show_new_changes == true`
  - we create a **BT Feature** with the above segment
- for user-facing features, we can check do a `feature_enabled?` check using the User's identifiers against the BT Feature, since it will be a single user anyway
- on the backend, there are background batch processes that we want to handle differently for User data with/without the new changes e.g. ignore data from Users with show_new_changes

It seemed like the only way to achieve the last point with our current setup was to run `feature_enabled?` for every single **User** in our DB every time the background process is run, which is very wasteful.

Is there another setup you would recommend?

**Comment by dabeeeenster** [comment]
Hi - We'll add this to the backlog - happy to take pull requests too!

**Comment by wasabigeek** [comment]
Thanks @dabeeeenster, do you have a recommended way of approaching this? In my mind we could do either `/identities/?trait_id=1&trait_value=xyz` or `/identities/?trait=value`

**Comment by matthewelwell** [comment]
Hey @wasabigeek, apologies for the delay in getting back to you and thanks for explaining the use case, it certainly makes sense. 

The problem with either of the above is that we would then be returning a different structure of data based on the query parameters provided (e.g. a list / single resource), which I don't particularly like. Now, I'd hasten to add that the above is probably the _correct_ way to do it and the code we have at the moment is probably, well, less correct but it's where we're at and I don't particularly want to go changing the API interface at this stage. 

So, based on that, I think we'll need to either: 

(a) Develop a totally new endpoint that lists the identities for an environment based on the API key and can be filtered on `trait_key` and `trait_value`
(b) Wait until we release the functionality to obtain API keys for the admin API that already has this functionality and we can add the filtering on traits there too. This would, however, mean a separate integration for your Backend application as we don't currently plan on including that functionality in our clients. 

Either way, I would suggest that the parameters would need to be `trait_key` and `trait_value` to fit the existing interface. And we would want to add some validation to ensure that if `trait_value` is provided then `trait_key` is provided as well.

Hopefully that makes sense?
