### ISSUE TITLE
Invalid HTTP_HOST header: 'bullettrain_api:8000'. The domain name provided is not valid according to RFC 1034/1035.

### ISSUE THREAD

**Issue by xtrmstep** [Flagsmith/flagsmith#63]
Hi,

I'm deploying Bullet-Train to Docker and trying to connect using aliases (container names). it seems there is a hardcode to check that the domain name is following RFC 1034/1035. I think this is not required.

Can it be removed or configured to disable this check?

Thanks,

**Comment by dabeeeenster** [comment]
Hi - can you provide further details - I'm not quite clear from the above exactly what you mean?

**Comment by xtrmstep** [comment]
@dabeeeenster 
I'm deploying with docker-compose web and api, and I've called the API service as `bullettrain_api`. With the name `bullettrain-api` it's absolutely fine.

So I thought it maybe not required to have such validation. Or maybe just mention somewhere in documentation, because it wasn't obvious why API isn't work.

Regards,

**Comment by dabeeeenster** [comment]
Sorry - when you say you've 'called' the api service `bullettrain_api` can you clarify?

**Comment by dabeeeenster** [comment]
I'm not sure it's a good idea making the application behave out of spec?

**Comment by xtrmstep** [comment]
@dabeeeenster I mean this https://prnt.sc/vbolo3

**Comment by dabeeeenster** [comment]
This is by design in Django - we wouldnt want to start changing this: https://code.djangoproject.com/ticket/18517?cversion=0&cnum_hist=4
