### ISSUE TITLE
WebHook doesn't work

### ISSUE THREAD

**Issue by GennadiiSvichinskyi** [Flagsmith/flagsmith#70]
Hi,

I'm trying to investigate how to use web hooks.
I've created test ASP.NET Core service and expose endpoint https://localhost:32768/feature-flags/feature-changed
Then I've added WebHook to our Dev environment (Bullet Train server runs on K8s in our corporate network)
When I click on Test WebHook button it is working perfectly.
But when I try to update/create/delete feture flag - nothing happens.
It seems that Flagsmith server doesn't know about web hook I've created.

**Comment by dabeeeenster** [comment]
Are you defining an Audit webhook or a Feature Webhook?
