### ISSUE TITLE
Sending project = 0 while creating a feature through the api leads to an internal server error

### ISSUE THREAD

**Issue by lehmamic** [Flagsmith/flagsmith#71]
I'm using the flagsmith api directly in our project. I'm creating a feature through the api =>

POST /api/v1/projects/{project}/features/ where the project property of the body is set to 0 and in the url to the project id.

This will cause an 500 internal server error, in my opinion it should return a 400 bad request instead.

**Comment by dabeeeenster** [comment]
Thanks for this report - will get on it!

**Comment by aman0408** [comment]
Can i take this up? If yes, could you please add the label "hacktoberfest-accepted" label to the issue?

**Comment by dabeeeenster** [comment]
Sure!

**Comment by aman0408** [comment]
Alright will take it up! Thanks!

**Comment by aman0408** [comment]
<img width="1248" alt="Screenshot 2021-10-24 at 11 01 03 AM" src="https://user-images.githubusercontent.com/42177948/138582137-069ec0e4-eb72-4f77-96ff-8ab8aa882f02.png">
Unable to replicate the issue. API return 403 since projects are created starting from id 1

**Comment by dabeeeenster** [comment]
Ah ok - well I'll close this then! Happy for you to work on something else!
