### ISSUE TITLE
Bug: Can't change user group members

### ISSUE THREAD

**Issue by DanHammond** [Flagsmith/flagsmith#74]
**Page**: project/{id}/environment/{id}/organisation-settings
**Suspected reproduction steps**: 
- Create a user
- Add them to a group
- Delete the user
- Create another user
- Try add this user to the group

**Outcome**:
- Fails to add user
- Shows wrong count of users for the group (still including deleted user)

**API response**:
400. User {id} does not exist in this organisation

**Note**:
Looks like it's still trying to post back the id for the deleted user

**Comment by milanjaros** [comment]
Confirming bug on both on-prem v2.7.3 and cloud.
```
POST https://api.flagsmith.com/api/v1/organisations/1213/groups/165/add-users/

{"user_ids":[1268]}
```
results in
```
HTTP 400 Bad Request
{"detail":"User 1268 does not exist in this organisation"}
```

Workaround:
1. Create a new group with the same users
2. Set proper Permissions to the new group in Project Settings
3. Delete the old group

To prevent this, remove a user from all groups before you delete him.
