### ISSUE TITLE
Potential Bug:  Can't disable new user registration with OAuth

### ISSUE THREAD

**Issue by manuphatak** [Flagsmith/flagsmith#79]
With Google OAuth enabled, I can't disable the ability for new users to create accounts, organizations, & projects -- primarily accounts.

I've tried setting `USER_CREATE_PERMISSIONS=djoser.permissions.CurrentUserOrAdmin` like the readme suggests. And  FWIW I've tried `USER_CREATE_PERMISSIONS=rest_framework.permissions.IsAdminUser`

Any ideas on how to do this?

**Comment by dabeeeenster** [comment]
Hi @manuphatak - we'll take a look.

**Comment by manuphatak** [comment]
Great, Thank you!

**Comment by matthewelwell** [comment]
Hi @manuphatak, I've worked on this and added a new environment variable that will allow you to disable the registration of new users via Google and Github. I plan to merge this into the master branch on Github shortly. However, after reading your issue again I'm not sure that is exactly what you're looking for. Could you describe a bit more around the issue you're experiencing please? 

To set some more context:

The `USER_CREATE_PERMISSIONS` setting is there to essentially prevent users from registering and only allows users to be added to the platform via invites. The same thing here would be to disable OAuth registration as I have mentioned above.

Regarding the ability to prevent users inviting new users & creating new projects, that's something that we support in our enterprise solution which benefits from a more fine grained permission model but is not something that we officially support for self hosted installs. Users will always be able to create new organisations, however.

**Comment by matthewelwell** [comment]
Ok, I think I now understand and have updated the setting mentioned above such that it prevents uninvited users from registering via any method without an email invite, otherwise the API will throw a 403 forbidden error. I think that should achieve what you're after and is a slightly nicer experience than setting the permission class as you've mentioned? Let me know if that sounds like it will work for you and I can get it merged in.

**Comment by manuphatak** [comment]
Hey, @matthewelwell, I believe the solution you described is exactly what I was looking for. 🎉 

The scenario is... 
- we're self-hosting
- we know everyone who's going to use the tool

The problem we want to solve...
- We want to lock down the app enough that random people can't create accounts.

**Comment by matthewelwell** [comment]
Hi @manuphatak, this is now resolved in the master branch and also in the v2.7.1 tag. Note that if you're running the FE as well, you'll need to make sure that the FE is at least running v2.7.0 as well.

**Comment by manuphatak** [comment]
Awesome, thank you, thank you, thank you!

**Comment by manuphatak** [comment]
I just launched the 2.7.1 container and it worked exactly as expected. 🎉    **Thank you all so much!**


![Screen Shot 2021-05-24 at 3 36 39 PM](https://user-images.githubusercontent.com/5052422/119415163-ea368780-bca5-11eb-9365-b9cfef4c388c.png)
