### ISSUE TITLE
Add Flagsmith's API to Postman's API Network

### ISSUE THREAD

**Issue by arlemi** [Flagsmith/flagsmith#80]
Hey there 👋 

We'd love to see the Flagsmith API on the [Postman API Network](https://www.postman.com/explore) along with other companies like Strapi, Microsoft, Twilio etc. 
I see you already work out of an OpenAPI spec so it'd be pretty easy to generate documentation from it and let your users fork it so they can start playing with the API. 

If that sounds interesting for you, you can read[ how to get started here](https://blog.postman.com/how-to-set-up-public-workspaces/) or let me know and I can share more about the benefits/help you with it! 🙂

**Comment by dabeeeenster** [comment]
Hi @arlemi  - we'd definitely like to be involved. Can you message us on our webchat at flagsmith.com ?

**Comment by arlemi** [comment]
@dabeeeenster Couldn't see a webchat on the page (even after disabling adblock) so I used the contact form. If it's easier you can also ping me directly at arlemi@postman.com :D
