### ISSUE TITLE
Feature: Slack notifications

### ISSUE THREAD

**Issue by kyle-ssg** [Flagsmith/flagsmith#83]
Original requirement is here: https://app.clubhouse.io/flagsmith/story/182/slack-integration
Code is in a feature branch in Gitlab (merge request 194) which can be migrated over to Github and using as a starting reference.

**Comment by gagantrivedi** [comment]
Env vars
    SLACK_CLIENT_ID
    SLACK_CLIENT_SECRET

To start the oath flow we make a get request to(with redirect_url query param)
https://{address}/api/v1/environments/<environment_key>/integrations/slack/oauth/
which redirects the user(after oauth) to our callback endpoint(with auth token)
The view set to configure a channel for an environment is hosted at:
/environments/{environment_api_key}/integrations/slack/

ps: you can use something like https://ngrok.com/ to test oauth callback

**Comment by kyle-ssg** [comment]
Frontend live under remote config "slack" in flag "integrations"
