### ISSUE TITLE
Edge API - Write Environments through API to DynamoDB

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#85]
Whenever any part of an Environment's state changes, trigger a write through of the entire Environment to DynamoDB.

**Comment by matthewelwell** [comment]
I have created a branch [here](https://github.com/Flagsmith/flagsmith/tree/feature/github-85/global-api--add-json-endpoints) which generates the JSON document ready for storing in DynamoDB.

We need to add signals or lifecycle hooks that when any of environment, project, organisation, features, environment feature states, (maybe others?) get saved, we generate the JSON document (using the `build_environment_dict` method available in the flag engine repository (I've just been adding the flag engine project to my python path so I can import it for now). Once we've generated the document, we need to create/update the record in DynamoDB.

Some things that we might need to consider:

 - There are models that get created when other models are created (e.g. FeatureState from a Feature, etc.). This could trigger a bit of a waterfall if we are updating the dynamo record for each of these. Do we care though? 

The first thing to do would be to create a package or module which gives us the functions we need to interact with DynamoDB. I'd say we probably want to use `boto3` for this but there may be better options out there? 

Reading the documentation [here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.put_item), it may not be quite as simple as dumping a JSON document. We may need to map the data into a format that defines the data type of each attribute.
